unsigned char Iterator_gem[] =
"class ListIterator{\n"
"    init(list){\n"
"        this.list = list;\n"
"        this.index = 0;\n"
"    }\n"
"    iterator(){\n"
"        return this;\n"
"    }\n"
"    hasNext(){\n"
"        return this.index < this.list.length();\n"
"    }\n"
"    next(){\n"
"        var ret = this.list[this.index];\n"
"        this.index = this.index + 1;\n"
"        return ret;\n"
"    }\n"
"}\n"
"\n"
"class StringIterator{\n"
"    init(str){\n"
"        this.str = str;\n"
"        this.index = 0;\n"
"    }\n"
"    iterator(){\n"
"        return this;\n"
"    }\n"
"    hasNext(){\n"
"        return this.index < this.str.length();\n"
"    }\n"
"    next(){\n"
"        var ret = this.str.charAt(this.index);\n"
"        this.index = this.index + 1;\n"
"        return ret;\n"
"    }\n"
"}\n";

unsigned int Iterator_gem_len = sizeof(Iterator_gem) - 1;
